package hr.fer.zemris.java.hw03.prob1;


/**
 * Class that represents one token generated by lexer.
 * It has one constructor and variables that are storing
 * informations about value of the token and type
 * 
 * @author Marko
 *
 */
public class Token {
	
	private TokenType type;
	private Object value;
	
	/**
	 * Consturctor.
	 * 
	 * @param type {@code TokenType}, type of token.
	 * @param value {@code Object}, value of token.
	 */
	public Token(TokenType type, Object value) {
		this.type = type;
		this.value = value;
	}
	
	/**
	 * Returns value of token.
	 * 
	 * @return {@code Object} value of token.
	 */
	public Object getValue() {
		return value;
	}
	
	
	/**
	 * Returns type of token.
	 * 
	 * @return {@code TokenType} type of token.
	 */
	public TokenType getType() {
		return type;
	}
	
	@Override
	public String toString() {
		return "(" +  getType() + ", " + getValue() + ")";
	}
	
	

}
