package hr.fer.zemris.java.custom.scripting.lexer;

/**
 * Class that represents one token generated by smart lexer.
 * It has one constructor and variables that are storing
 * informations about value of the token and type
 * 
 * @author Marko
 *
 */
public class SmartToken {

	
	private SmartTokenType type;
	private Object value;
	
	
	/**
	 * Consturctor.
	 * 
	 * @param type {@code SmartTokenType}, type of token.
	 * @param value {@code Object}, value of token.
	 */
	public SmartToken(SmartTokenType type, Object value) {
		this.type = type;
		this.value = value;
	}
	
	/**
	 * Returns value of token.
	 * 
	 * @return {@code Object} value of token.
	 */
	public Object getValue() {
		return value;
	}
	
	
	/**
	 * Returns type of token.
	 * 
	 * @return {@code TokenType} type of token.
	 */
	public SmartTokenType getType() {
		return type;
	}
	
	@Override
	public String toString() {
		return "(" +  getType() + ", " + getValue() + ")";
	}
}
